apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: tetrate-istiod
  namespace: tetrate-istio-system
spec:
  chart:
    spec:
      chart: tetrate-istio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tetrate-istio-charts
        namespace: flux-system
      version: 1.18.1
  values:
    tid-base:
      defaultRevision: ""
    revision: 1-18-1
    tid-cni:
      revision: 1-18-1
    global:
      istioNamespace: tetrate-istio-system
  interval: 1m0s
